/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AudioProcessor */

#ifndef _Included_AudioProcessor
#define _Included_AudioProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AudioProcessor
 * Method:    sinewave
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AudioProcessor_AudioStart
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_AudioProcessor_Volume
  (JNIEnv* env, jobject this_obj, jdouble min, jdouble max);  

#ifdef __cplusplus
}
#endif
#endif
